spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "c9kdtZ4l6AgUTt1OOtC5aZGKBbTz/gB2ajf7uY98PHhLAm4CFk4QapzvbCYUXPrI"
    username: "1JQrJLS5kCF2sbM9L3mT5w=="
    password: "kzFgh/OxvV8sA6UPnmKRiw=="
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
      
server:
  port : 8081
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  config-location: classpath:mybatis-config.xml